spring:
  profiles:
    active: local

  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  profiles: local
  datasource:
      url: jdbc:mariadb://localhost:3306/settle_batch
      username: root
      password: 678900
      driver-class-name: org.mariadb.jdbc.Driver
---
spring:
  profiles: mysql
  datasource:
      url: jdbc:mariadb://localhost:3306/settle_batch
      username: root
      password: 678900
      driver-class-name: org.mariadb.jdbc.Driver